// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.minio.outputs.GetIamPolicyDocumentStatement;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetIamPolicyDocumentResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private final String id;
    private final String json;
    private final @Nullable String overrideJson;
    private final @Nullable String policyId;
    private final @Nullable String sourceJson;
    private final @Nullable List<GetIamPolicyDocumentStatement> statements;
    private final @Nullable String version;

    @CustomType.Constructor
    private GetIamPolicyDocumentResult(
        @CustomType.Parameter("id") String id,
        @CustomType.Parameter("json") String json,
        @CustomType.Parameter("overrideJson") @Nullable String overrideJson,
        @CustomType.Parameter("policyId") @Nullable String policyId,
        @CustomType.Parameter("sourceJson") @Nullable String sourceJson,
        @CustomType.Parameter("statements") @Nullable List<GetIamPolicyDocumentStatement> statements,
        @CustomType.Parameter("version") @Nullable String version) {
        this.id = id;
        this.json = json;
        this.overrideJson = overrideJson;
        this.policyId = policyId;
        this.sourceJson = sourceJson;
        this.statements = statements;
        this.version = version;
    }

    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String json() {
        return this.json;
    }
    public Optional<String> overrideJson() {
        return Optional.ofNullable(this.overrideJson);
    }
    public Optional<String> policyId() {
        return Optional.ofNullable(this.policyId);
    }
    public Optional<String> sourceJson() {
        return Optional.ofNullable(this.sourceJson);
    }
    public List<GetIamPolicyDocumentStatement> statements() {
        return this.statements == null ? List.of() : this.statements;
    }
    public Optional<String> version() {
        return Optional.ofNullable(this.version);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetIamPolicyDocumentResult defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private String id;
        private String json;
        private @Nullable String overrideJson;
        private @Nullable String policyId;
        private @Nullable String sourceJson;
        private @Nullable List<GetIamPolicyDocumentStatement> statements;
        private @Nullable String version;

        public Builder() {
    	      // Empty
        }

        public Builder(GetIamPolicyDocumentResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.json = defaults.json;
    	      this.overrideJson = defaults.overrideJson;
    	      this.policyId = defaults.policyId;
    	      this.sourceJson = defaults.sourceJson;
    	      this.statements = defaults.statements;
    	      this.version = defaults.version;
        }

        public Builder id(String id) {
            this.id = Objects.requireNonNull(id);
            return this;
        }
        public Builder json(String json) {
            this.json = Objects.requireNonNull(json);
            return this;
        }
        public Builder overrideJson(@Nullable String overrideJson) {
            this.overrideJson = overrideJson;
            return this;
        }
        public Builder policyId(@Nullable String policyId) {
            this.policyId = policyId;
            return this;
        }
        public Builder sourceJson(@Nullable String sourceJson) {
            this.sourceJson = sourceJson;
            return this;
        }
        public Builder statements(@Nullable List<GetIamPolicyDocumentStatement> statements) {
            this.statements = statements;
            return this;
        }
        public Builder statements(GetIamPolicyDocumentStatement... statements) {
            return statements(List.of(statements));
        }
        public Builder version(@Nullable String version) {
            this.version = version;
            return this;
        }        public GetIamPolicyDocumentResult build() {
            return new GetIamPolicyDocumentResult(id, json, overrideJson, policyId, sourceJson, statements, version);
        }
    }
}
