provider: minio
major-version: 1
docker: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
env:
    MINIO_ENDPOINT: localhost:9000
    MINIO_ACCESS_KEY: minio
    MINIO_SECRET_KEY: minio123
    MINIO_ENABLE_HTTPS: false
makeTemplate: bridged
team: ecosystem
pulumiConvert: 1
registryDocs: true
checkUpstreamUpgrade: false
