// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.minio.IamGroupMembershipArgs;
import com.pulumi.minio.Utilities;
import com.pulumi.minio.inputs.IamGroupMembershipState;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

@ResourceType(type="minio:index/iamGroupMembership:IamGroupMembership")
public class IamGroupMembership extends com.pulumi.resources.CustomResource {
    /**
     * Group name to add users
     * 
     */
    @Export(name="group", refs={String.class}, tree="[0]")
    private Output<String> group;

    /**
     * @return Group name to add users
     * 
     */
    public Output<String> group() {
        return this.group;
    }
    /**
     * Name of group membership
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Name of group membership
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Add user or list of users such as a group membership
     * 
     */
    @Export(name="users", refs={List.class,String.class}, tree="[0,1]")
    private Output<List<String>> users;

    /**
     * @return Add user or list of users such as a group membership
     * 
     */
    public Output<List<String>> users() {
        return this.users;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public IamGroupMembership(java.lang.String name) {
        this(name, IamGroupMembershipArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public IamGroupMembership(java.lang.String name, IamGroupMembershipArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public IamGroupMembership(java.lang.String name, IamGroupMembershipArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("minio:index/iamGroupMembership:IamGroupMembership", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private IamGroupMembership(java.lang.String name, Output<java.lang.String> id, @Nullable IamGroupMembershipState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("minio:index/iamGroupMembership:IamGroupMembership", name, state, makeResourceOptions(options, id), false);
    }

    private static IamGroupMembershipArgs makeArgs(IamGroupMembershipArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? IamGroupMembershipArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static IamGroupMembership get(java.lang.String name, Output<java.lang.String> id, @Nullable IamGroupMembershipState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new IamGroupMembership(name, id, state, options);
    }
}
