// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.minio.IamGroupPolicyArgs;
import com.pulumi.minio.Utilities;
import com.pulumi.minio.inputs.IamGroupPolicyState;
import java.lang.String;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.minio.IamGroup;
 * import com.pulumi.minio.IamGroupPolicy;
 * import com.pulumi.minio.IamGroupPolicyArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var developer = new IamGroup(&#34;developer&#34;);
 * 
 *         var testPolicy = new IamGroupPolicy(&#34;testPolicy&#34;, IamGroupPolicyArgs.builder()        
 *             .group(developer.id())
 *             .policy(&#34;&#34;&#34;
 * {
 *   &#34;Version&#34;:&#34;2012-10-17&#34;,
 *   &#34;Statement&#34;: [
 *     {
 *       &#34;Sid&#34;:&#34;ListAllBucket&#34;,
 *       &#34;Effect&#34;: &#34;Allow&#34;,
 *       &#34;Action&#34;: [&#34;s3:PutObject&#34;],
 *       &#34;Principal&#34;:&#34;*&#34;,
 *       &#34;Resource&#34;: &#34;arn:aws:s3:::state-terraform-s3/*&#34;
 *     }
 *   ]
 * }
 * 
 *             &#34;&#34;&#34;)
 *             .build());
 * 
 *         ctx.export(&#34;minioName&#34;, minio_iam_group_membership.developer().id());
 *         ctx.export(&#34;minioPolicy&#34;, minio_iam_group_membership.developer().policy());
 *         ctx.export(&#34;minioGroup&#34;, minio_iam_group_membership.developer().group());
 *     }
 * }
 * ```
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 */
@ResourceType(type="minio:index/iamGroupPolicy:IamGroupPolicy")
public class IamGroupPolicy extends com.pulumi.resources.CustomResource {
    @Export(name="group", refs={String.class}, tree="[0]")
    private Output<String> group;

    public Output<String> group() {
        return this.group;
    }
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    public Output<String> name() {
        return this.name;
    }
    @Export(name="namePrefix", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> namePrefix;

    public Output<Optional<String>> namePrefix() {
        return Codegen.optional(this.namePrefix);
    }
    @Export(name="policy", refs={String.class}, tree="[0]")
    private Output<String> policy;

    public Output<String> policy() {
        return this.policy;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public IamGroupPolicy(String name) {
        this(name, IamGroupPolicyArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public IamGroupPolicy(String name, IamGroupPolicyArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public IamGroupPolicy(String name, IamGroupPolicyArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("minio:index/iamGroupPolicy:IamGroupPolicy", name, args == null ? IamGroupPolicyArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private IamGroupPolicy(String name, Output<String> id, @Nullable IamGroupPolicyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("minio:index/iamGroupPolicy:IamGroupPolicy", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static IamGroupPolicy get(String name, Output<String> id, @Nullable IamGroupPolicyState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new IamGroupPolicy(name, id, state, options);
    }
}
