// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.minio.S3BucketVersioningArgs;
import com.pulumi.minio.Utilities;
import com.pulumi.minio.inputs.S3BucketVersioningState;
import com.pulumi.minio.outputs.S3BucketVersioningVersioningConfiguration;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.minio.S3Bucket;
 * import com.pulumi.minio.S3BucketArgs;
 * import com.pulumi.minio.S3BucketVersioning;
 * import com.pulumi.minio.S3BucketVersioningArgs;
 * import com.pulumi.minio.inputs.S3BucketVersioningVersioningConfigurationArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var bucketS3Bucket = new S3Bucket(&#34;bucketS3Bucket&#34;, S3BucketArgs.builder()        
 *             .bucket(&#34;example-bucket&#34;)
 *             .build());
 * 
 *         var bucketS3BucketVersioning = new S3BucketVersioning(&#34;bucketS3BucketVersioning&#34;, S3BucketVersioningArgs.builder()        
 *             .bucket(bucketS3Bucket.bucket())
 *             .versioningConfiguration(S3BucketVersioningVersioningConfigurationArgs.builder()
 *                 .status(&#34;Enabled&#34;)
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="minio:index/s3BucketVersioning:S3BucketVersioning")
public class S3BucketVersioning extends com.pulumi.resources.CustomResource {
    @Export(name="bucket", type=String.class, parameters={})
    private Output<String> bucket;

    public Output<String> bucket() {
        return this.bucket;
    }
    @Export(name="versioningConfiguration", type=S3BucketVersioningVersioningConfiguration.class, parameters={})
    private Output<S3BucketVersioningVersioningConfiguration> versioningConfiguration;

    public Output<S3BucketVersioningVersioningConfiguration> versioningConfiguration() {
        return this.versioningConfiguration;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public S3BucketVersioning(String name) {
        this(name, S3BucketVersioningArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public S3BucketVersioning(String name, S3BucketVersioningArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public S3BucketVersioning(String name, S3BucketVersioningArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("minio:index/s3BucketVersioning:S3BucketVersioning", name, args == null ? S3BucketVersioningArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private S3BucketVersioning(String name, Output<String> id, @Nullable S3BucketVersioningState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("minio:index/s3BucketVersioning:S3BucketVersioning", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static S3BucketVersioning get(String name, Output<String> id, @Nullable S3BucketVersioningState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new S3BucketVersioning(name, id, state, options);
    }
}
