// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.minio.S3BucketServerSideEncryptionArgs;
import com.pulumi.minio.Utilities;
import com.pulumi.minio.inputs.S3BucketServerSideEncryptionState;
import java.lang.String;
import javax.annotation.Nullable;

@ResourceType(type="minio:index/s3BucketServerSideEncryption:S3BucketServerSideEncryption")
public class S3BucketServerSideEncryption extends com.pulumi.resources.CustomResource {
    @Export(name="bucket", refs={String.class}, tree="[0]")
    private Output<String> bucket;

    public Output<String> bucket() {
        return this.bucket;
    }
    @Export(name="encryptionType", refs={String.class}, tree="[0]")
    private Output<String> encryptionType;

    public Output<String> encryptionType() {
        return this.encryptionType;
    }
    @Export(name="kmsKeyId", refs={String.class}, tree="[0]")
    private Output<String> kmsKeyId;

    public Output<String> kmsKeyId() {
        return this.kmsKeyId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public S3BucketServerSideEncryption(java.lang.String name) {
        this(name, S3BucketServerSideEncryptionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public S3BucketServerSideEncryption(java.lang.String name, S3BucketServerSideEncryptionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public S3BucketServerSideEncryption(java.lang.String name, S3BucketServerSideEncryptionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("minio:index/s3BucketServerSideEncryption:S3BucketServerSideEncryption", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private S3BucketServerSideEncryption(java.lang.String name, Output<java.lang.String> id, @Nullable S3BucketServerSideEncryptionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("minio:index/s3BucketServerSideEncryption:S3BucketServerSideEncryption", name, state, makeResourceOptions(options, id), false);
    }

    private static S3BucketServerSideEncryptionArgs makeArgs(S3BucketServerSideEncryptionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? S3BucketServerSideEncryptionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static S3BucketServerSideEncryption get(java.lang.String name, Output<java.lang.String> id, @Nullable S3BucketServerSideEncryptionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new S3BucketServerSideEncryption(name, id, state, options);
    }
}
