// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package minio

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-minio/sdk/go/minio/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the minio package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// Minio Access Key
	//
	// Deprecated: use minioUser instead
	MinioAccessKey pulumi.StringPtrOutput `pulumi:"minioAccessKey"`
	// Minio API Version (type: string, options: v2 or v4, default: v4)
	MinioApiVersion pulumi.StringPtrOutput `pulumi:"minioApiVersion"`
	MinioCacertFile pulumi.StringPtrOutput `pulumi:"minioCacertFile"`
	MinioCertFile   pulumi.StringPtrOutput `pulumi:"minioCertFile"`
	MinioKeyFile    pulumi.StringPtrOutput `pulumi:"minioKeyFile"`
	// Minio Password
	MinioPassword pulumi.StringPtrOutput `pulumi:"minioPassword"`
	// Minio Region (default: us-east-1)
	MinioRegion pulumi.StringPtrOutput `pulumi:"minioRegion"`
	// Minio Secret Key
	//
	// Deprecated: use minioPassword instead
	MinioSecretKey pulumi.StringPtrOutput `pulumi:"minioSecretKey"`
	// Minio Host and Port
	MinioServer pulumi.StringPtrOutput `pulumi:"minioServer"`
	// Minio Session Token
	MinioSessionToken pulumi.StringPtrOutput `pulumi:"minioSessionToken"`
	// Minio User
	MinioUser pulumi.StringPtrOutput `pulumi:"minioUser"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:minio", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// Minio Access Key
	//
	// Deprecated: use minioUser instead
	MinioAccessKey *string `pulumi:"minioAccessKey"`
	// Minio API Version (type: string, options: v2 or v4, default: v4)
	MinioApiVersion *string `pulumi:"minioApiVersion"`
	MinioCacertFile *string `pulumi:"minioCacertFile"`
	MinioCertFile   *string `pulumi:"minioCertFile"`
	// Disable SSL certificate verification (default: false)
	MinioInsecure *bool   `pulumi:"minioInsecure"`
	MinioKeyFile  *string `pulumi:"minioKeyFile"`
	// Minio Password
	MinioPassword *string `pulumi:"minioPassword"`
	// Minio Region (default: us-east-1)
	MinioRegion *string `pulumi:"minioRegion"`
	// Minio Secret Key
	//
	// Deprecated: use minioPassword instead
	MinioSecretKey *string `pulumi:"minioSecretKey"`
	// Minio Host and Port
	MinioServer *string `pulumi:"minioServer"`
	// Minio Session Token
	MinioSessionToken *string `pulumi:"minioSessionToken"`
	// Minio SSL enabled (default: false)
	MinioSsl *bool `pulumi:"minioSsl"`
	// Minio User
	MinioUser *string `pulumi:"minioUser"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// Minio Access Key
	//
	// Deprecated: use minioUser instead
	MinioAccessKey pulumi.StringPtrInput
	// Minio API Version (type: string, options: v2 or v4, default: v4)
	MinioApiVersion pulumi.StringPtrInput
	MinioCacertFile pulumi.StringPtrInput
	MinioCertFile   pulumi.StringPtrInput
	// Disable SSL certificate verification (default: false)
	MinioInsecure pulumi.BoolPtrInput
	MinioKeyFile  pulumi.StringPtrInput
	// Minio Password
	MinioPassword pulumi.StringPtrInput
	// Minio Region (default: us-east-1)
	MinioRegion pulumi.StringPtrInput
	// Minio Secret Key
	//
	// Deprecated: use minioPassword instead
	MinioSecretKey pulumi.StringPtrInput
	// Minio Host and Port
	MinioServer pulumi.StringPtrInput
	// Minio Session Token
	MinioSessionToken pulumi.StringPtrInput
	// Minio SSL enabled (default: false)
	MinioSsl pulumi.BoolPtrInput
	// Minio User
	MinioUser pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
func (r *Provider) TerraformConfig(ctx *pulumi.Context) (ProviderTerraformConfigResultOutput, error) {
	out, err := ctx.Call("pulumi:providers:minio/terraformConfig", nil, ProviderTerraformConfigResultOutput{}, r)
	if err != nil {
		return ProviderTerraformConfigResultOutput{}, err
	}
	return out.(ProviderTerraformConfigResultOutput), nil
}

type ProviderTerraformConfigResult struct {
	Result map[string]interface{} `pulumi:"result"`
}

type ProviderTerraformConfigResultOutput struct{ *pulumi.OutputState }

func (ProviderTerraformConfigResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderTerraformConfigResult)(nil)).Elem()
}

func (o ProviderTerraformConfigResultOutput) Result() pulumi.MapOutput {
	return o.ApplyT(func(v ProviderTerraformConfigResult) map[string]interface{} { return v.Result }).(pulumi.MapOutput)
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// Minio Access Key
//
// Deprecated: use minioUser instead
func (o ProviderOutput) MinioAccessKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioAccessKey }).(pulumi.StringPtrOutput)
}

// Minio API Version (type: string, options: v2 or v4, default: v4)
func (o ProviderOutput) MinioApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioApiVersion }).(pulumi.StringPtrOutput)
}

func (o ProviderOutput) MinioCacertFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioCacertFile }).(pulumi.StringPtrOutput)
}

func (o ProviderOutput) MinioCertFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioCertFile }).(pulumi.StringPtrOutput)
}

func (o ProviderOutput) MinioKeyFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioKeyFile }).(pulumi.StringPtrOutput)
}

// Minio Password
func (o ProviderOutput) MinioPassword() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioPassword }).(pulumi.StringPtrOutput)
}

// Minio Region (default: us-east-1)
func (o ProviderOutput) MinioRegion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioRegion }).(pulumi.StringPtrOutput)
}

// Minio Secret Key
//
// Deprecated: use minioPassword instead
func (o ProviderOutput) MinioSecretKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioSecretKey }).(pulumi.StringPtrOutput)
}

// Minio Host and Port
func (o ProviderOutput) MinioServer() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioServer }).(pulumi.StringPtrOutput)
}

// Minio Session Token
func (o ProviderOutput) MinioSessionToken() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioSessionToken }).(pulumi.StringPtrOutput)
}

// Minio User
func (o ProviderOutput) MinioUser() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.MinioUser }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
	pulumi.RegisterOutputType(ProviderTerraformConfigResultOutput{})
}
