// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.minio.inputs.GetIamPolicyDocumentStatementCondition;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetIamPolicyDocumentStatement extends com.pulumi.resources.InvokeArgs {

    public static final GetIamPolicyDocumentStatement Empty = new GetIamPolicyDocumentStatement();

    @Import(name="actions")
    private @Nullable List<String> actions;

    public Optional<List<String>> actions() {
        return Optional.ofNullable(this.actions);
    }

    @Import(name="conditions")
    private @Nullable List<GetIamPolicyDocumentStatementCondition> conditions;

    public Optional<List<GetIamPolicyDocumentStatementCondition>> conditions() {
        return Optional.ofNullable(this.conditions);
    }

    @Import(name="effect")
    private @Nullable String effect;

    public Optional<String> effect() {
        return Optional.ofNullable(this.effect);
    }

    @Import(name="principal")
    private @Nullable String principal;

    public Optional<String> principal() {
        return Optional.ofNullable(this.principal);
    }

    @Import(name="resources")
    private @Nullable List<String> resources;

    public Optional<List<String>> resources() {
        return Optional.ofNullable(this.resources);
    }

    @Import(name="sid")
    private @Nullable String sid;

    public Optional<String> sid() {
        return Optional.ofNullable(this.sid);
    }

    private GetIamPolicyDocumentStatement() {}

    private GetIamPolicyDocumentStatement(GetIamPolicyDocumentStatement $) {
        this.actions = $.actions;
        this.conditions = $.conditions;
        this.effect = $.effect;
        this.principal = $.principal;
        this.resources = $.resources;
        this.sid = $.sid;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetIamPolicyDocumentStatement defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetIamPolicyDocumentStatement $;

        public Builder() {
            $ = new GetIamPolicyDocumentStatement();
        }

        public Builder(GetIamPolicyDocumentStatement defaults) {
            $ = new GetIamPolicyDocumentStatement(Objects.requireNonNull(defaults));
        }

        public Builder actions(@Nullable List<String> actions) {
            $.actions = actions;
            return this;
        }

        public Builder actions(String... actions) {
            return actions(List.of(actions));
        }

        public Builder conditions(@Nullable List<GetIamPolicyDocumentStatementCondition> conditions) {
            $.conditions = conditions;
            return this;
        }

        public Builder conditions(GetIamPolicyDocumentStatementCondition... conditions) {
            return conditions(List.of(conditions));
        }

        public Builder effect(@Nullable String effect) {
            $.effect = effect;
            return this;
        }

        public Builder principal(@Nullable String principal) {
            $.principal = principal;
            return this;
        }

        public Builder resources(@Nullable List<String> resources) {
            $.resources = resources;
            return this;
        }

        public Builder resources(String... resources) {
            return resources(List.of(resources));
        }

        public Builder sid(@Nullable String sid) {
            $.sid = sid;
            return this;
        }

        public GetIamPolicyDocumentStatement build() {
            return $;
        }
    }

}
