// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IamServiceAccountState extends com.pulumi.resources.ResourceArgs {

    public static final IamServiceAccountState Empty = new IamServiceAccountState();

    @Import(name="accessKey")
    private @Nullable Output<String> accessKey;

    public Optional<Output<String>> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    /**
     * Disable service account
     * 
     */
    @Import(name="disableUser")
    private @Nullable Output<Boolean> disableUser;

    /**
     * @return Disable service account
     * 
     */
    public Optional<Output<Boolean>> disableUser() {
        return Optional.ofNullable(this.disableUser);
    }

    /**
     * policy of service account
     * 
     */
    @Import(name="policy")
    private @Nullable Output<String> policy;

    /**
     * @return policy of service account
     * 
     */
    public Optional<Output<String>> policy() {
        return Optional.ofNullable(this.policy);
    }

    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    @Import(name="status")
    private @Nullable Output<String> status;

    public Optional<Output<String>> status() {
        return Optional.ofNullable(this.status);
    }

    @Import(name="targetUser")
    private @Nullable Output<String> targetUser;

    public Optional<Output<String>> targetUser() {
        return Optional.ofNullable(this.targetUser);
    }

    /**
     * rotate secret key
     * 
     */
    @Import(name="updateSecret")
    private @Nullable Output<Boolean> updateSecret;

    /**
     * @return rotate secret key
     * 
     */
    public Optional<Output<Boolean>> updateSecret() {
        return Optional.ofNullable(this.updateSecret);
    }

    private IamServiceAccountState() {}

    private IamServiceAccountState(IamServiceAccountState $) {
        this.accessKey = $.accessKey;
        this.disableUser = $.disableUser;
        this.policy = $.policy;
        this.secretKey = $.secretKey;
        this.status = $.status;
        this.targetUser = $.targetUser;
        this.updateSecret = $.updateSecret;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IamServiceAccountState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IamServiceAccountState $;

        public Builder() {
            $ = new IamServiceAccountState();
        }

        public Builder(IamServiceAccountState defaults) {
            $ = new IamServiceAccountState(Objects.requireNonNull(defaults));
        }

        public Builder accessKey(@Nullable Output<String> accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        public Builder accessKey(String accessKey) {
            return accessKey(Output.of(accessKey));
        }

        /**
         * @param disableUser Disable service account
         * 
         * @return builder
         * 
         */
        public Builder disableUser(@Nullable Output<Boolean> disableUser) {
            $.disableUser = disableUser;
            return this;
        }

        /**
         * @param disableUser Disable service account
         * 
         * @return builder
         * 
         */
        public Builder disableUser(Boolean disableUser) {
            return disableUser(Output.of(disableUser));
        }

        /**
         * @param policy policy of service account
         * 
         * @return builder
         * 
         */
        public Builder policy(@Nullable Output<String> policy) {
            $.policy = policy;
            return this;
        }

        /**
         * @param policy policy of service account
         * 
         * @return builder
         * 
         */
        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        public Builder status(@Nullable Output<String> status) {
            $.status = status;
            return this;
        }

        public Builder status(String status) {
            return status(Output.of(status));
        }

        public Builder targetUser(@Nullable Output<String> targetUser) {
            $.targetUser = targetUser;
            return this;
        }

        public Builder targetUser(String targetUser) {
            return targetUser(Output.of(targetUser));
        }

        /**
         * @param updateSecret rotate secret key
         * 
         * @return builder
         * 
         */
        public Builder updateSecret(@Nullable Output<Boolean> updateSecret) {
            $.updateSecret = updateSecret;
            return this;
        }

        /**
         * @param updateSecret rotate secret key
         * 
         * @return builder
         * 
         */
        public Builder updateSecret(Boolean updateSecret) {
            return updateSecret(Output.of(updateSecret));
        }

        public IamServiceAccountState build() {
            return $;
        }
    }

}
