// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class IamUserPolicyAttachmentState extends com.pulumi.resources.ResourceArgs {

    public static final IamUserPolicyAttachmentState Empty = new IamUserPolicyAttachmentState();

    @Import(name="policyName")
    private @Nullable Output<String> policyName;

    public Optional<Output<String>> policyName() {
        return Optional.ofNullable(this.policyName);
    }

    @Import(name="userName")
    private @Nullable Output<String> userName;

    public Optional<Output<String>> userName() {
        return Optional.ofNullable(this.userName);
    }

    private IamUserPolicyAttachmentState() {}

    private IamUserPolicyAttachmentState(IamUserPolicyAttachmentState $) {
        this.policyName = $.policyName;
        this.userName = $.userName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(IamUserPolicyAttachmentState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private IamUserPolicyAttachmentState $;

        public Builder() {
            $ = new IamUserPolicyAttachmentState();
        }

        public Builder(IamUserPolicyAttachmentState defaults) {
            $ = new IamUserPolicyAttachmentState(Objects.requireNonNull(defaults));
        }

        public Builder policyName(@Nullable Output<String> policyName) {
            $.policyName = policyName;
            return this;
        }

        public Builder policyName(String policyName) {
            return policyName(Output.of(policyName));
        }

        public Builder userName(@Nullable Output<String> userName) {
            $.userName = userName;
            return this;
        }

        public Builder userName(String userName) {
            return userName(Output.of(userName));
        }

        public IamUserPolicyAttachmentState build() {
            return $;
        }
    }

}
