// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class S3BucketPolicyState extends com.pulumi.resources.ResourceArgs {

    public static final S3BucketPolicyState Empty = new S3BucketPolicyState();

    @Import(name="bucket")
    private @Nullable Output<String> bucket;

    public Optional<Output<String>> bucket() {
        return Optional.ofNullable(this.bucket);
    }

    @Import(name="policy")
    private @Nullable Output<String> policy;

    public Optional<Output<String>> policy() {
        return Optional.ofNullable(this.policy);
    }

    private S3BucketPolicyState() {}

    private S3BucketPolicyState(S3BucketPolicyState $) {
        this.bucket = $.bucket;
        this.policy = $.policy;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(S3BucketPolicyState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private S3BucketPolicyState $;

        public Builder() {
            $ = new S3BucketPolicyState();
        }

        public Builder(S3BucketPolicyState defaults) {
            $ = new S3BucketPolicyState(Objects.requireNonNull(defaults));
        }

        public Builder bucket(@Nullable Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        public Builder policy(@Nullable Output<String> policy) {
            $.policy = policy;
            return this;
        }

        public Builder policy(String policy) {
            return policy(Output.of(policy));
        }

        public S3BucketPolicyState build() {
            return $;
        }
    }

}
