// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.minio.inputs.S3BucketVersioningVersioningConfigurationArgs;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class S3BucketVersioningState extends com.pulumi.resources.ResourceArgs {

    public static final S3BucketVersioningState Empty = new S3BucketVersioningState();

    @Import(name="bucket")
    private @Nullable Output<String> bucket;

    public Optional<Output<String>> bucket() {
        return Optional.ofNullable(this.bucket);
    }

    @Import(name="versioningConfiguration")
    private @Nullable Output<S3BucketVersioningVersioningConfigurationArgs> versioningConfiguration;

    public Optional<Output<S3BucketVersioningVersioningConfigurationArgs>> versioningConfiguration() {
        return Optional.ofNullable(this.versioningConfiguration);
    }

    private S3BucketVersioningState() {}

    private S3BucketVersioningState(S3BucketVersioningState $) {
        this.bucket = $.bucket;
        this.versioningConfiguration = $.versioningConfiguration;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(S3BucketVersioningState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private S3BucketVersioningState $;

        public Builder() {
            $ = new S3BucketVersioningState();
        }

        public Builder(S3BucketVersioningState defaults) {
            $ = new S3BucketVersioningState(Objects.requireNonNull(defaults));
        }

        public Builder bucket(@Nullable Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        public Builder versioningConfiguration(@Nullable Output<S3BucketVersioningVersioningConfigurationArgs> versioningConfiguration) {
            $.versioningConfiguration = versioningConfiguration;
            return this;
        }

        public Builder versioningConfiguration(S3BucketVersioningVersioningConfigurationArgs versioningConfiguration) {
            return versioningConfiguration(Output.of(versioningConfiguration));
        }

        public S3BucketVersioningState build() {
            return $;
        }
    }

}
