// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.minio.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class S3BucketServerSideEncryptionState extends com.pulumi.resources.ResourceArgs {

    public static final S3BucketServerSideEncryptionState Empty = new S3BucketServerSideEncryptionState();

    @Import(name="bucket")
    private @Nullable Output<String> bucket;

    public Optional<Output<String>> bucket() {
        return Optional.ofNullable(this.bucket);
    }

    @Import(name="encryptionType")
    private @Nullable Output<String> encryptionType;

    public Optional<Output<String>> encryptionType() {
        return Optional.ofNullable(this.encryptionType);
    }

    @Import(name="kmsKeyId")
    private @Nullable Output<String> kmsKeyId;

    public Optional<Output<String>> kmsKeyId() {
        return Optional.ofNullable(this.kmsKeyId);
    }

    private S3BucketServerSideEncryptionState() {}

    private S3BucketServerSideEncryptionState(S3BucketServerSideEncryptionState $) {
        this.bucket = $.bucket;
        this.encryptionType = $.encryptionType;
        this.kmsKeyId = $.kmsKeyId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(S3BucketServerSideEncryptionState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private S3BucketServerSideEncryptionState $;

        public Builder() {
            $ = new S3BucketServerSideEncryptionState();
        }

        public Builder(S3BucketServerSideEncryptionState defaults) {
            $ = new S3BucketServerSideEncryptionState(Objects.requireNonNull(defaults));
        }

        public Builder bucket(@Nullable Output<String> bucket) {
            $.bucket = bucket;
            return this;
        }

        public Builder bucket(String bucket) {
            return bucket(Output.of(bucket));
        }

        public Builder encryptionType(@Nullable Output<String> encryptionType) {
            $.encryptionType = encryptionType;
            return this;
        }

        public Builder encryptionType(String encryptionType) {
            return encryptionType(Output.of(encryptionType));
        }

        public Builder kmsKeyId(@Nullable Output<String> kmsKeyId) {
            $.kmsKeyId = kmsKeyId;
            return this;
        }

        public Builder kmsKeyId(String kmsKeyId) {
            return kmsKeyId(Output.of(kmsKeyId));
        }

        public S3BucketServerSideEncryptionState build() {
            return $;
        }
    }

}
