// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface GetIamPolicyDocumentStatement {
    actions?: string[];
    conditions?: inputs.GetIamPolicyDocumentStatementCondition[];
    effect?: string;
    principal?: string;
    resources?: string[];
    sid?: string;
}

export interface GetIamPolicyDocumentStatementArgs {
    actions?: pulumi.Input<pulumi.Input<string>[]>;
    conditions?: pulumi.Input<pulumi.Input<inputs.GetIamPolicyDocumentStatementConditionArgs>[]>;
    effect?: pulumi.Input<string>;
    principal?: pulumi.Input<string>;
    resources?: pulumi.Input<pulumi.Input<string>[]>;
    sid?: pulumi.Input<string>;
}

export interface GetIamPolicyDocumentStatementCondition {
    test: string;
    values: string[];
    variable: string;
}

export interface GetIamPolicyDocumentStatementConditionArgs {
    test: pulumi.Input<string>;
    values: pulumi.Input<pulumi.Input<string>[]>;
    variable: pulumi.Input<string>;
}
