// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetIamPolicyDocumentStatement {
    actions?: string[];
    conditions?: inputs.GetIamPolicyDocumentStatementCondition[];
    effect?: string;
    principal?: string;
    resources?: string[];
    sid?: string;
}

export interface GetIamPolicyDocumentStatementArgs {
    actions?: pulumi.Input<pulumi.Input<string>[]>;
    conditions?: pulumi.Input<pulumi.Input<inputs.GetIamPolicyDocumentStatementConditionArgs>[]>;
    effect?: pulumi.Input<string>;
    principal?: pulumi.Input<string>;
    resources?: pulumi.Input<pulumi.Input<string>[]>;
    sid?: pulumi.Input<string>;
}

export interface GetIamPolicyDocumentStatementCondition {
    test: string;
    values: string[];
    variable: string;
}

export interface GetIamPolicyDocumentStatementConditionArgs {
    test: pulumi.Input<string>;
    values: pulumi.Input<pulumi.Input<string>[]>;
    variable: pulumi.Input<string>;
}

export interface IlmPolicyRule {
    expiration?: pulumi.Input<string>;
    filter?: pulumi.Input<string>;
    /**
     * The ID of this resource.
     */
    id: pulumi.Input<string>;
    status?: pulumi.Input<string>;
    tags?: pulumi.Input<{[key: string]: any}>;
}

export interface S3BucketNotificationQueue {
    events: pulumi.Input<pulumi.Input<string>[]>;
    filterPrefix?: pulumi.Input<string>;
    filterSuffix?: pulumi.Input<string>;
    /**
     * The ID of this resource.
     */
    id?: pulumi.Input<string>;
    queueArn: pulumi.Input<string>;
}

export interface S3BucketVersioningVersioningConfiguration {
    excludeFolders?: pulumi.Input<boolean>;
    excludedPrefixes?: pulumi.Input<pulumi.Input<string>[]>;
    status: pulumi.Input<string>;
}
