// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Minio.Inputs
{

    public sealed class S3BucketNotificationQueueGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("events", required: true)]
        private InputList<string>? _events;
        public InputList<string> Events
        {
            get => _events ?? (_events = new InputList<string>());
            set => _events = value;
        }

        [Input("filterPrefix")]
        public Input<string>? FilterPrefix { get; set; }

        [Input("filterSuffix")]
        public Input<string>? FilterSuffix { get; set; }

        [Input("id")]
        public Input<string>? Id { get; set; }

        [Input("queueArn", required: true)]
        public Input<string> QueueArn { get; set; } = null!;

        public S3BucketNotificationQueueGetArgs()
        {
        }
        public static new S3BucketNotificationQueueGetArgs Empty => new S3BucketNotificationQueueGetArgs();
    }
}
