// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ## Example Usage
 */
export class IamUserPolicyAttachment extends pulumi.CustomResource {
    /**
     * Get an existing IamUserPolicyAttachment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IamUserPolicyAttachmentState, opts?: pulumi.CustomResourceOptions): IamUserPolicyAttachment {
        return new IamUserPolicyAttachment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'minio:index/iamUserPolicyAttachment:IamUserPolicyAttachment';

    /**
     * Returns true if the given object is an instance of IamUserPolicyAttachment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IamUserPolicyAttachment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IamUserPolicyAttachment.__pulumiType;
    }

    declare public readonly policyName: pulumi.Output<string>;
    declare public readonly userName: pulumi.Output<string>;

    /**
     * Create a IamUserPolicyAttachment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: IamUserPolicyAttachmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IamUserPolicyAttachmentArgs | IamUserPolicyAttachmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IamUserPolicyAttachmentState | undefined;
            resourceInputs["policyName"] = state?.policyName;
            resourceInputs["userName"] = state?.userName;
        } else {
            const args = argsOrState as IamUserPolicyAttachmentArgs | undefined;
            if (args?.policyName === undefined && !opts.urn) {
                throw new Error("Missing required property 'policyName'");
            }
            if (args?.userName === undefined && !opts.urn) {
                throw new Error("Missing required property 'userName'");
            }
            resourceInputs["policyName"] = args?.policyName;
            resourceInputs["userName"] = args?.userName;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IamUserPolicyAttachment.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IamUserPolicyAttachment resources.
 */
export interface IamUserPolicyAttachmentState {
    policyName?: pulumi.Input<string>;
    userName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IamUserPolicyAttachment resource.
 */
export interface IamUserPolicyAttachmentArgs {
    policyName: pulumi.Input<string>;
    userName: pulumi.Input<string>;
}
